# Run docker-compose run -d
# drush config-import
# If running Linux, make sure /persistent/iiifcache has 100:100 ownership
# If running Linux, make sure /persistent/solrcore has 8983:8983 ownership
# enabling :cache for the volumens can bypass that need.
# on OSX brew install minio/stable/mc for the minio client
version: '3.5'
services:
  web:
    container_name: esmero-web
    restart: always
    image: "nginx"
    depends_on:
      - solr
      - php
    tty: true
    ports:
      - "8001:80"
    networks:
      - host-net
      - esmero-net
    volumes:
      - ${PWD}/nginxconfigford8/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}:/var/www/html:cached
  php:
    container_name: esmero-php
    restart: always
    image: "esmero/php-7.4-fpm:1.0.0-RC2-multiarch"
    tty: true
    networks:
      - host-net
      - esmero-net
    volumes:
      - ${PWD}:/var/www/html:cached
  solr:
    container_name: esmero-solr
    restart: always
    image: "solr:8.8.2"
    tty: true
    ports:
      - "8983:8983"
    networks:
      - host-net
      - esmero-net
    volumes:
      - ${PWD}/persistent/solrcore:/var/solr/data:cached
      - ${PWD}/persistent/solrconfig:/drupalconfig:cached
      - ${PWD}/persistent/solrlib:/opt/solr/contrib/archipelago/lib:cached
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - drupal
      - /drupalconfig
 # see https://hub.docker.com/_/mysql/
  db:
    image: mysql:8.0.22
    command: mysqld --default-authentication-plugin=mysql_native_password  --max_allowed_packet=256M --sort_buffer_size=512K --binlog-expire-logs-seconds=172800
    container_name: esmero-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: esmerodb
    networks:
      - host-net
      - esmero-net
    volumes:
      - ${PWD}/persistent/db:/var/lib/mysql:cached
  nlp:
    container_name: esmero-nlp
    restart: always
    image: "esmero/esmero-nlp:1.0"
    ports:
      - "6400:6400"
    networks:
      - host-net
      - esmero-net
  iiif:
    container_name: esmero-cantaloupe
    image: "esmero/cantaloupe-s3:4.1.9RC"
    restart: always
    environment:
      XMX: 2g
      XMS: 256m
    ports:
      - "8183:8182"
    networks:
      - host-net
      - esmero-net
    volumes:
      - ${PWD}/persistent/iiifconfig:/etc/cantaloupe
      - ${PWD}/persistent/iiifcache:/var/cache/cantaloupe

  minio:
    container_name: esmero-minio
    restart: always
    image: minio/minio:latest
    volumes:
         - ${PWD}/persistent/miniodata:/data:cached
    ports:
         - "9000:9000"
         - "9001:9001"
    networks:
      - host-net
      - esmero-net
    environment:
         MINIO_ROOT_USER: minio
         MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
networks:
  host-net:
    driver: bridge
  esmero-net:
    driver: bridge
    internal: true
