version: '3.6'
services:
  web:
    environment:
      - PHP_IDE_CONFIG=serverName=$DDEV_HOSTNAME
      - XDEBUG_CONFIG=discover_client_host=On
      # Enable Drush Launcher Xdebug compatibility.
      # @see https://github.com/drush-ops/drush-launcher#xdebug-compatibility
      - DRUSH_ALLOW_XDEBUG=1
      - SIMPLETEST_BASE_URL=http://$DDEV_HOSTNAME
      - SIMPLETEST_DB=mysql://root:root@db/drupal
      - BROWSERTEST_OUTPUT_DIRECTORY=/tmp
#      - SYMFONY_DEPRECATIONS_HELPER=weak
